services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress-data:/var/www/html/
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb-data:/var/lib/mysql/
    env_file:
      - .env
    restart: always
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-check", "$MARIADB_DBNAME"]
      interval: 10s
      timeout: 10s
      retries: 20

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/snaji/data/wordpress'
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/snaji/data/mariadb'

networks:
  inception:
    driver: bridge
