services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "6969:443"
    volumes:
      - wordpress-data:/var/www/html/

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress-data:/var/www/html/
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb-data:/var/lib/mysql/
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mariadb-check", "$MARIADB_DBNAME"]
      interval: 2s
      timeout: 10s
      retries: 10

volumes:
  wordpress-data:
  mariadb-data: