services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "6969:90"
    volumes:
      - wordpress-data:/usr/share/nginx/html/

  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - wordpress-data:/usr/share/wordpress/

  mariadb:
    build: ./requirements/mariadb/
    volumes:
      - mariadb-data:/var/lib/mysql/

volumes:
  wordpress-data:
  mariadb-data: