FROM alpine:3.18

RUN apk add --no-cache php82 \
    php82-common \
    php82-fpm \
    php82-pdo \
    php82-opcache \
    php82-zip \
    php82-phar \
    php82-iconv \
    php82-cli \
    php82-curl \
    php82-openssl \
    php82-mbstring \
    php82-tokenizer \
    php82-fileinfo \
    php82-json \
    php82-xml \
    php82-xmlwriter \
    php82-simplexml \
    php82-dom \
    php82-pdo_mysql \
    php82-pdo_sqlite \
    php82-tokenizer \
    php82-pecl-redis\
	php82-mysqli \
	curl

RUN mkdir /code/

COPY ./install_wordpress.sh /code/install_wordpress.sh

CMD chmod +x /code/install_wordpress.sh && /code/install_wordpress.sh